# Generated by Django 5.0.6 on 2024-07-27 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consumer',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('Phone', models.BigIntegerField(null=True)),
                ('Gender', models.TextField(max_length=10, null=True)),
                ('Address', models.TextField(max_length=1000, null=True)),
                ('Password', models.TextField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller_reg',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('Seller_name', models.TextField(max_length=100, null=True)),
                ('Photo', models.ImageField(upload_to='sell_photo/')),
                ('Seller_email', models.EmailField(max_length=100, null=True)),
                ('Phone', models.BigIntegerField(null=True)),
                ('Gender', models.TextField(max_length=10, null=True)),
                ('Address', models.TextField(max_length=1000, null=True)),
                ('Password', models.TextField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('Product', models.TextField(max_length=100, null=True)),
                ('product_Photo', models.ImageField(upload_to='prod_img/')),
                ('Specification', models.TextField(max_length=300)),
                ('Quantity', models.IntegerField(null=True)),
                ('Price', models.IntegerField(null=True)),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.seller_reg')),
            ],
        ),
    ]
