# Generated by Django 5.0.6 on 2024-07-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_reg',
            name='Photo',
            field=models.ImageField(upload_to='static/sell_photo/'),
        ),
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('buyeddate', models.DateTimeField(auto_created=True)),
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('sellerid', models.IntegerField()),
                ('product_name', models.TextField(max_length=100)),
                ('product_image', models.ImageField(upload_to='static/buyer/')),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('seller_contact_number', models.BigIntegerField()),
                ('seller_email_id', models.EmailField(max_length=100)),
                ('buyerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('Date', models.DateTimeField(auto_created=True)),
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('Seller_email', models.EmailField(max_length=100)),
                ('Product', models.TextField(max_length=100, null=True)),
                ('product_Photo', models.ImageField(upload_to='static/prod_img/')),
                ('Specification', models.TextField(max_length=300)),
                ('Quantity', models.IntegerField(null=True)),
                ('Price', models.IntegerField(null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.seller_reg')),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
