# Generated by Django 5.0.6 on 2024-07-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_seller_reg_photo_buyer_products_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
