# Generated by Django 5.0.6 on 2024-07-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_products_date_alter_products_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Specification',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
