# Generated by Django 5.0.6 on 2024-07-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_products_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='Seller_address',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='Seller_name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyeddate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
