# Generated by Django 5.0.6 on 2024-08-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_buyer_seller_address_buyer_seller_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='product_image',
            field=models.ImageField(upload_to='buyer/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_Photo',
            field=models.ImageField(upload_to='prod_img/'),
        ),
    ]
